
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exampleniosci(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY
	

);

		platformniosci u0 (
		.clk_clk       (CLOCK_50),       //   clk.clk
		.reset_reset_n (KEY[0])          // reset.reset_n
	   );

endmodule
